name: data_science
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - pip
  - pyvis
  - requests
  - scikit-learn
  - seaborn
  - tqdm
  - pytest
  - pip:
    - gensim
    - jupyter
    - matplotlib
    - networkx
    - nltk
    - spacy
    - squarify
